language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
before_install:
 - chmod +x ./gradlew
 - chmod +x ./gradlew.bat
install: gradle assemble
script: gradle check
   #- ./StudyAtNanterre/gradlew build